name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (bezkoder-ui)
        run: docker build ./bezkoder-ui -t nullone01/bezkoder-ui
      
      - name: Build Docker image (bezkoder-api)
        run: docker build ./bezkoder-api -t nullone01/bezkoder-api

      - name: Push Docker image (bezkoder-ui)
        run: docker push nullone01/bezkoder-ui

      - name: Push Docker image (bezkoder-api)
        run: docker push nullone01/bezkoder-api
